version: '3.8'

services:
  cleanmails:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - LEVEL1_CONCURRENCY=200
      - LEVEL2_CONCURRENCY=50
      - SMTP_FROM_EMAIL=verify@yourdomain.com
      - SMTP_HELO_NAME=verify.yourdomain.com
      - SMTP_CATCH_ALL=true
    restart: always
